project_id = "mugtabvbojomcgdrxfli"

[functions.chat]
verify_jwt = true

[functions.compute-climate]
verify_jwt = false

[functions.generate-visualization]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.migrate-guest-requests]
verify_jwt = false

[functions.process-site-request]
verify_jwt = false

[functions.design-assistant]
verify_jwt = false

[functions.design-assistant-stream]
verify_jwt = false

[functions.send-completion-email]
verify_jwt = false
